### ISSUE TITLE
Missing dependencies? Cannot build.

### ISSUE THREAD

**Issue by brett-doffing** [BlockchainCommons/GordianWallet-iOS#1]
Right now it looks like LibWally is the only pod installed,  should others be as well? Cannot build because it is missing at least KeychainSwift and Tor.

**Comment by Fonta1n3** [comment]
Sorry I really need to update the readme... Will fix that asap. For tor.framework and KeychainSwift.framework you need to use carthage: ‘cd FullyNoded2’ and run ‘carthage update —platform iOS’ and let it do its thing. A project clean or restart of xcode may be needed. 

you may need xcode command line tools as a dependency. Will add detailed instructions shortly to the readme.

**Comment by Fonta1n3** [comment]
More detailed instructions are now on the readme. Please let me know if it works for you. If not let me know the snag and I can help.

https://github.com/BlockchainCommons/FullyNoded-2#build-from-source

**Comment by brett-doffing** [comment]
Dependencies are good to go now.
