### ISSUE TITLE
Cannot add a signer

### ISSUE THREAD

**Issue by mflaxman** [BlockchainCommons/GordianWallet-iOS#100]
I'm following the instructions in https://github.com/BlockchainCommons/GordianWallet-iOS/issues/96

```
And to use Gordian as a signer for this quorum, you:

    Accounts > tap your account to "activate it"
    Tap the tools button in top right
    Tap add a signer
```

When I add a signer, I'm trying to input the phrase `defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense another` but there's no submit button or way forward:

![IMG_1091](https://user-images.githubusercontent.com/448644/95685572-3e30a800-0bbe-11eb-873c-ee47a070dcfe.PNG)

I also can't see past word #18 in case I had any typos, but that's a separate UI issue.

**Comment by Fonta1n3** [comment]
Hmm it automatically checks if the mnemonic is valid and prompts you. Will make that view scrollable.

**Comment by ChristopherA** [comment]
Be careful, there are 24 word BIP39 mnemonics where the first 12 words are also a valid mnemonic.

**Comment by Fonta1n3** [comment]
@mflaxman @ChristopherA Looks like Libwally does not recognize `defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense another` as a valid bip39 mnemonic, will need to raise an issue there.

**Comment by Fonta1n3** [comment]
#97 fixes the issue of the view not being scrollable, unfortunately fixing Libwally to recognize that as a valid mnemonic is going to take more time, perhaps they have some sort of minimum entropy required? Every single mnemonic I have ever tested works except that one...

**Comment by Fonta1n3** [comment]
Hve raised this issue on the Libwally repo [https://github.com/ElementsProject/libwally-core/issues/234](https://github.com/ElementsProject/libwally-core/issues/234)

**Comment by Fonta1n3** [comment]
> @mflaxman @ChristopherA Looks like Libwally does not recognize `defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense defense another` as a valid bip39 mnemonic, will need to raise an issue there.

This is incorrect, it was a bug on my part where I was only checking for 12 words mnemonics when "refilling the keypool" or "adding a signer", actually recovering an account with a 24 word mnemonic was not effected which is why it slipped through the cracks. Good find.
