### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mflaxman** [BlockchainCommons/GordianWallet-iOS#101]
![IMG_1094](https://user-images.githubusercontent.com/448644/95685648-c0b96780-0bbe-11eb-9c51-3bba30a3b830.png)
`more info please` is not clickable.

I'm trying to test if it's possible to use Gordian Wallet as a cosigner, so these types of things are much less important. But, figured I'd mention it while I'm here.

**Comment by mflaxman** [comment]
FYI: I got this page by clicking the QR code icon in the upper right of https://github.com/BlockchainCommons/GordianWallet-iOS/issues/100

**Comment by Fonta1n3** [comment]
Definitely appreciate any and all issues! Fixed in #97 

I am uploading 0.1.90 now, if you would like instant access I would be happy to add you to our internal testing team, I would need your apple ID email to add you though, otherwise the update should be live in next 12 to 24 hours.
