### ISSUE TITLE
BUG / POOR ERROR MESSAGE: v0.1.90 "Error Getting MuSig Address"

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianWallet-iOS#102]
Trying to sending testnet hot account funds from my iOS Simulator single sig PR #97, to my iOS Wallet multisig testflight 0.1.90 warm account from last month. When I click on get invoice on I get "Error Getting MuSig Address".

It could be that you've deleted the keys from the shared testnet node. However, if this is what happened, a) the fact it was missing should have been reported earlier when I selected the account. b) this message is useless for a regular user to figuring out what was wrong or even be able to report back to us what was wrong.

![IMG_3670](https://user-images.githubusercontent.com/69103/95788790-0d6d7300-0c91-11eb-96ad-019965742f45.PNG)
![File Oct 12, 1 35 23 PM](https://user-images.githubusercontent.com/69103/95788800-13fbea80-0c91-11eb-87eb-79b1f9434b81.jpeg)

**Comment by ChristopherA** [comment]
Note that a second attempt to change account, change back, etc. resulting in that I could get invoice (though there were several errors along the way which I should have captured), but finally I was able later to get an address. So the fullnode keys are there. Instead, there are other problems, and in any case, the error still does't have enough detail to tell a user what to do now.

**Comment by Fonta1n3** [comment]
#104 addresses this error message so that it should be more descriptive and 0.1.91 on Testflight.
