### ISSUE TITLE
UX: Update info on switch to Accounts Pane after change in balance from Home refresh or X time

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianWallet-iOS#103]
I refreshed my Home Pane to show my first balance change for my test warm wallet. However, when I switch to the Accounts pane, it shows a 0 balance for that same account.

I should not have to also manually refresh the Accounts Pane to see that balance that the Home screen already was refreshed to see. 

Related, if you go to Accounts Pane, and there has been some significant delay since last refresh, it probably should do a refresh. It probably should not do a refresh every time you to to pane. Similarly, the Home Pane may need the same feature, but maybe a different amount of time.

**Comment by Fonta1n3** [comment]
this has been addressed in #104 and 0.1.91 Testflight
