### ISSUE TITLE
Building still requires Carthage

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianWallet-iOS#105]
Despite @Fonta1n3 saying there is no Carthage code anymore in the base, if you try to build without `brew carthage` being installed first, the build will fail:

```
/Users/admin/Library/Developer/Xcode/DerivedData/GordianWallet-byfkhpctudycydatqhyeeeiwvfqj/Build/Intermediates.noindex/GordianWallet.build/Debug-iphonesimulator/GordianWallet.build/Script-D09D727323F0F1F800847DC8.sh: line 2: /usr/local/bin/carthage: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

We are not sure which package is causing this, but Peter thinks it might be some relic in the LibWally library. @wolfmcnally — when you are looking at our libraries this week, could you try to track this down?

**Comment by Fonta1n3** [comment]
This would be much more appropriate to raise under the actual BCLibwallySwift repo: [https://github.com/BlockchainCommons/BCLibwallySwift](https://github.com/BlockchainCommons/BCLibwallySwift)

**Comment by wolfmcnally** [comment]
I think this has been handled now?

**Comment by Fonta1n3** [comment]
> I think this has been handled now?

last build Christopher did worked fine without Carthage so I will close this for now.
