### ISSUE TITLE
Testflight Down

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianWallet-iOS#120]
I noticed my beta had expired. When I tried to renew it by going to the Testflight link, I got "This beta isn't accepting any new testers right now."

![UNADJUSTEDNONRAW_thumb_55fd](https://user-images.githubusercontent.com/1110886/108128077-532bb500-7050-11eb-9a40-775723159b05.jpg)

**Comment by shannona** [comment]
We've got a new version; Wallet remains invite only

**Comment by ChristopherA** [comment]
I'm reopening as the public TestFlight is still down.

**Comment by Fonta1n3** [comment]
@ChristopherA You requested that I fix the TestFlight, I did that but of course did not have time to test the huge amount of changes that were required. Public TestFlight is intentionally down until the latest release is tested more.

For now it will be internal only.

**Comment by artk42** [comment]
We'd be happy to join TestFlight for feedback and reporting, public testflight is still down

**Comment by wolfmcnally** [comment]
@Fonta1n3 Please check to make sure your TestFlight release has been submitted for Apple's Beta Review. Users get this message if there is no currently approved binary.

**Comment by Fonta1n3** [comment]
> @Fonta1n3 Please check to make sure your TestFlight release has been submitted for Apple's Beta Review. Users get this message if there is no currently approved binary.

Thanks @wolfmcnally, currently I do not have access to upload builds for public testflight. @ChristopherA are you aware the public testflight is still down?

**Comment by shannona** [comment]
Have removed Testflight links, as we are not currently running Testflight for Gordian Wallet.
