### ISSUE TITLE
Cannot build.

### ISSUE THREAD

**Issue by brett-doffing** [BlockchainCommons/GordianWallet-iOS#16]
'origins' is inaccessible due to 'internal' protection level

ScannerViewController, line 174 `let origins = input.origins`

**Comment by Fonta1n3** [comment]
I assumed changes I make to the LibWally pod would be reflected in my commits... I guess not. Yea we need to access the path property directly to do offline signing of PSBT's. To fix you can open "project navigator" -> "Pods" -> "Pods" -> "LibWally" -> "PSBT.swift" -> and change `let path: BIP32Path` on line 14 to `public let path: BIP32Path`. Will submit a PR to LibWally-Swift to see if they can expose it so we only need to do minimal alterations. FYI there is a [bug](https://github.com/blockchain/libwally-swift/pull/31) with PSBT signing in the library where it only works for multi-sig transactions.

**Comment by brett-doffing** [comment]
Should I close an issue such as this if it is not fully resolved by the dependency?

**Comment by Fonta1n3** [comment]
AFAIAC if the info I gave you allows you to build the app then the issue can be closed. Probably worth adding to the readme that the library needs to be slightly modified for the app to build from source though and worth submitting a PR to LibWally-Swift to see if they are ok making those changes so we do not have to. They have already made a few on our behalf.

**Comment by brett-doffing** [comment]
Actually had to make `let origins: [PubKey: KeyOrigin]?` `public` on line 36 as well. At this point we're just hacking away at a dependency just to get things to work, which I do not recommend.

**Comment by Fonta1n3** [comment]
I would suggest submitting a PR to LibWally-Swift.
