### ISSUE TITLE
'privKey' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by brett-doffing** [BlockchainCommons/GordianWallet-iOS#3]
It seems there are two cases where privKey of HDKey (LibWally) is trying to be accessed. In KeyFetcher.swift, line 51, and ExportKeysViewController.swift, line 403. Project will not build. I modified the code to get it to build, but do not know the consequences of this as that is all I was trying to do.

**Comment by Fonta1n3** [comment]
Yep that needs to be modified, we need to be able to fetch private keys to sign the transactions throughout the app so making that variable public is the fix. You can see this [issue](https://github.com/blockchain/libwally-swift/issues/20) for background.

**Comment by Fonta1n3** [comment]
This is modified and I do not see any negative consequences, we just need to be careful with how we use the private keys. Closing for now.
