### ISSUE TITLE
QR scan crash.

### ISSUE THREAD

**Issue by brett-doffing** [BlockchainCommons/GordianWallet-iOS#7]
`if let hostCheck = URLComponents(string: url)?.host` in QuickConnect continues successfully when no host exists in the URI, but other values do. Line 35 `if arr[0].count == 56` then causes a crash since index 0 is out of range for an empty array.

**Comment by Fonta1n3** [comment]
This was fixed in https://github.com/BlockchainCommons/FullyNoded-2/pull/11
