### ISSUE TITLE
No way to exit QR code scanner

### ISSUE THREAD

**Issue by mflaxman** [BlockchainCommons/GordianWallet-iOS#98]
X in upper right doesn't do anything.

You can force-quit the app and restart, but that's obviously not ideal.
![IMG_1089](https://user-images.githubusercontent.com/448644/95684778-679b0500-0bb9-11eb-9d42-1d73f5f0cff1.PNG)

**Comment by ChristopherA** [comment]
I have this same new bug when building it from Xcode too. Never seen this one before.

Did you get the series of informational screens telling you about GordianWallet, agreeing to license, and doing your first Apple Auth to lock your wallet keys. Did you see these before getting this scan window?

My best guess is that when adding new QR PSBT mechanism somehow it is coming up too soon if you’ve never initialized the app before it is popping up the scan window, and it can’t be exited as the app is not properly set up.

It is weekend, so hopefully tomorrow or Tuesday we’ll get an update.

**Comment by Fonta1n3** [comment]
Had just done a major refactor of QR scanning and missed hooking up that button. Will fix today, you can always swipe the scanner down to dismiss it as with any modally presented view.

**Comment by Fonta1n3** [comment]
#97 fixes this
